- name: populate package facts
  package_facts:
- name: install auditd
  apt:
    name: auditd
    state: present
  register: apt_status
  until: apt_status is success
  retries: 12
  delay: 10
- name: touch stig.rules
  file:
    path: /etc/audit/rules.d/stig.rules
    state: touch
    mode: '0640'
    modification_time: preserve
    access_time: preserve
# R-238197 UBTU-20-010002
- name: stigrule_238197__etc_gdm3_greeter_dconf_defaults_enable
  ini_file:
    path: /etc/gdm3/greeter.dconf-defaults
    section: org/gnome/login-screen
    option: banner-message-enable
    value: "{{ ubuntu2004STIG_stigrule_238197__etc_gdm3_greeter_dconf_defaults_enable_Value }}"
    # value: "Hello"
    no_extra_spaces: yes
  notify: dconf_update
  when:
    - ubuntu2004STIG_stigrule_238197_Manage
    - "'gdm3' in packages"
# R-238198 UBTU-20-010003
- name: stigrule_238198__etc_gdm3_greeter_dconf_defaults_text
  ini_file:
    path: /etc/gdm3/greeter.dconf-defaults
    section: org/gnome/login-screen
    option: banner-message-text
    value: "{{ ubuntu2004STIG_stigrule_238198__etc_gdm3_greeter_dconf_defaults_text_Value }}"
    no_extra_spaces: yes
  notify: dconf_update
  when:
    - ubuntu2004STIG_stigrule_238198_Manage
    - "'gdm3' in packages"
# R-238200 UBTU-20-010005
- name: stigrule_238200_vlock
  apt:
    name: vlock
    # state: "{{ ubuntu2004STIG_stigrule_238200_vlock_State }}"
    state: "absent"
    update_cache: yes
  register: apt_status
  until: apt_status is success
  retries: 12
  delay: 10
  when: ubuntu2004STIG_stigrule_238200_Manage
