---
- hosts: localhost
  gather_facts: no
  become: true
  roles:
    - ubuntu2004STIG
  tasks:
    - debug: msg="Stig Check Completed"
    - pause:
        seconds: 5
    - name: Get current date and time
      set_fact:
        current_datetime: "{{ lookup('pipe', 'TZ=America/Chicago date +\"%Y-%m-%d_%H%M%S\"') }}"

    - name: Generate HTML report from XML
      convert_xml_to_html:
        xml_file_path: "./stig_result/results_new.xml"
        html_file_path: "./stig_result/{{ current_datetime }}_ubuntu_stig_report.html"
      become: false

